# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_code', models.TextField(blank=True, help_text='Custom JavaScript: Copy and paste it on this field.', null=True, verbose_name='JS code')),
                ('ga_account', models.CharField(blank=True, help_text='Google Analitics Tracking ID', max_length=32, null=True, verbose_name='GA Tracking ID')),
                ('last_update', models.DateTimeField(db_column='last_update_time', default=django.utils.timezone.now, editable=False, verbose_name='last update time')),
                ('mkeyword', models.TextField(blank=True, help_text='Site meta keywords. Please write a comma separated.', null=True, verbose_name='Meta keywords')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'site parameter',
                'verbose_name_plural': 'site parameters',
                'db_table': 'element_siteparam',
            },
        ),
    ]
